export * from './blue/blue';
export * from './bold/bold';
export * from './color/color';
export * from './green/green';
export * from './italic/italic';
export * from './lg/lg';
export * from './md/md';
export * from './red/red';
export * from './xl/xl';
